name: Bug
description: Reporte de problema
title: "[bug] "
labels: ["bug"]
body:
  - type: textarea
    id: pasos
    attributes:
      label: Pasos para reproducir
      description: Paso a paso.
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: Resultado esperado
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Resultado actual
    validations:
      required: true

  - type: input
    id: entorno
    attributes:
      label: Entorno
      description: Navegador / dispositivo / URL
