name: Feature request
description: Propuesta de mejora o nueva funcionalidad
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - sergiodelgado

body:
  - type: textarea
    id: problem
    attributes:
      label: Problema u oportunidad
      description: ¿Qué problema real se quiere resolver?
      placeholder: Ej. Dificultad para entender rápidamente el foco profesional del sitio.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Propuesta
      description: Describe la solución propuesta, a alto nivel.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      description: Condiciones objetivas para considerar la feature terminada.
      placeholder: |
        - El cambio es visible en producción
        - No rompe CI
        - Mantiene el diseño minimal
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notas adicionales
      description: Riesgos, alternativas, dependencias.
    validations:
      required: false
